summrize/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from . import views
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.HomepageView.as_view(), name='home'),
    url(r'^text/', include("text.urls", namespace="text")),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    (r'^static/(.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT
    }),
    (r'^media/(.*)$','django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT
    }),
)

text/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.FeedView.as_view(), name="Feed"),
    url(r'^submit', views.TextAdd.as_view(), name="Submit"),
)

text/models.py
from django.db import models
from django. template.defaultfilters import slugify
from model_utils.models import TimeStampedModel

# Create your models here.
class Text(TimeStampedModel):
    mean_scored_text = models.TextField()
    top_n_scored_text = models.TextField()
    title = models.CharField(max_length=255, default='Text')
    slug = models.SlugField(max_length=255)
    date = models.DateTimeField(auto_now_add=True, editable=False)
    objects = models.Manager()

    # Set output format to unicode
    def __unicode__(self):
        return u'{0}'.format(self.title)

    # Save slug method
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Text, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return("")

text/forms.py
from django.forms import ModelForm
from .models import Text

class TextForm(ModelForm):
    class Meta:
        model = Text
        fields = ['title']

summrize/views.py
from django.views.generic import TemplateView

class HomepageView(TemplateView):
    template_name = "submit.html"

text/views.py
from django.views.generic import ListView, CreateView
from .models import Text
from .forms import TextForm
from text_summarize import *
from django.http import HttpResponseRedirect

class FeedView(ListView):
    model = Text
    template_name = 'feed.html'
    paginate_by = 5

    def get_queryset(self):
        return self.model.objects.all().order_by('-date')

class TextAdd(CreateView):
    model = Text
    form_class = TextForm
    success_url = '/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        summarized_text = summarize(form.data['text'],int(form.data['num_sentences']))
        self.object.mean_scored_text = summarized_text[0].encode('latin1','ignore')
        self.object.top_n_scored_text = summarized_text[1].encode('latin1','ignore')
        self.object.title = form.data['title']
        self.object.save()
        return HttpResponseRedirect('/text/')

    def form_invalid(self, form):
        print form.errors
        return HttpResponseRedirect('/')

summrize/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %} Title here {% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css"/>
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather+Sans:400,800' rel='stylesheet' type='text/css'>
    {% block css-link %} {% endblock %}
</head>
<body>
    <header>
        <nav>
            <h1><a href="/text">Summrize</a></h1>
            {% block buttons %}
            {% endblock %}
        </nav>
    </header>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
<footer>

</footer>
</html>

text/templates/errors.html
<ul class="errorlist"><li>top_n_scored_text<ul class="errorlist"><li>This field is required.</li></ul></li><li>mean_scored_text<ul class="errorlist"><li>This field is required.</li></ul></li></ul>

text/templates/feed.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block css-link %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/feed.css"/>
{% endblock %}

{% block title %}
Summrize | Feed
{% endblock %}

{% block buttons %}
    <form action="/" id="back">
        <button>Submit text</button>
    </form>
{% endblock %}

{% block content %}
    <ul>
        {% for entry in text_list %}
        <li>
            <h3>{{ entry.title }} <span>| Date posted: {{ entry.date }}</span></h3>
            <h4>Mean Scored Summary</h4>
            <p>{{ entry.mean_scored_text }}</p>
            <h4>Top N Sentences</h4>
            <p>{{ entry.top_n_scored_text }}</p>
        </li>
        {% endfor %}
        {% if is_paginated %}
            <div class="pagination">
                {% if page_obj.has_previous %}
                    <a id="previous" href="/text?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                {% if page_obj.has_next %}
                    <a id="next" href="/text?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </div>
        {% endif %}
    </ul>
{% endblock %}

text/templates/submit.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block css-link %}
    <script type="text/javascript"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/submit.css"/>
{% endblock %}

{% block title %}
Summrize | Enter text
{% endblock %}

{% block content %}
    <h3>Enter title, text and click summarize:</h3>
    <form action="/text/submit/" method="post" id="submit_text">
        {% csrf_token %}
        <input type="text" name="title" id="title" placeholder="Title"/>
        <textarea name="text" id="" cols="25" rows="25" placeholder="Enter text"></textarea>
        <label for="">Number of sentences:</label>
        <input type="text" name="num_sentences"/>
        <input type="submit" value="Summarize"/>
    </form>
{% endblock %}